%% Positive examples generated by generate_training_data.py
% Seed=42

:- begin_in_pos.

%% ── Category: knownTrue (65 examples) ──
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(1,3),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(3,4),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,3),cell(3,2),cell(3,1),cell(4,1),cell(4,2),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(4,4)]),eatwumpus(orTrue,[])],
       [stench], cell(3,4), knownTrue).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(3,2),cell(4,2),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [stench], cell(3,1), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,1),cell(3,3),cell(2,4),cell(3,4),cell(1,4),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(1,3),cell(1,4),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(3,3),cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,1),cell(4,2),cell(4,3)]),eatwumpus(orTrue,[])],
       [stench], cell(3,3), knownTrue).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,1),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,1),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(3,2), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3),cell(1,3),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(1,3),cell(2,4),cell(1,4),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(1,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(2,4),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,2),cell(3,1),cell(4,1),cell(4,2),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(3,3), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(3,1),cell(4,1),cell(4,2),cell(4,3),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[cell(4,1),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(4,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[])],
       [stench], cell(3,2), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(4,4),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(2,4),cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(1,3),cell(1,4),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(3,2),cell(4,3),cell(4,4),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(3,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(3,2), knownTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(2,3),cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(3,4),cell(4,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [stench], cell(1,3), knownTrue).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,1),cell(3,3),cell(2,4),cell(3,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,1)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(4,1), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(2,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(3,3),cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,1),cell(4,2),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(3,3), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(4,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(4,3),cell(3,4),cell(1,3),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[])],
       [stench], cell(4,1), knownTrue).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(3,2),cell(4,2),cell(3,1),cell(4,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(3,2),cell(4,3),cell(4,4),cell(4,2),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(3,3),cell(1,3),cell(2,4),cell(1,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(1,3),cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(4,3),cell(4,4),cell(3,4)]),eatwumpus(orTrue,[])],
       [stench], cell(2,4), knownTrue).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [stench], cell(3,4), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(2,4),cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,2),cell(4,2),cell(3,3),cell(3,1),cell(4,3),cell(3,4),cell(4,4),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(1,3),cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(3,2),cell(4,3),cell(4,4),cell(4,2),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,1),cell(3,3),cell(2,4),cell(3,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(4,4),cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,1),cell(4,3),cell(3,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,1),cell(1,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3),cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3),cell(4,3),cell(3,2),cell(4,2),cell(3,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownTrue).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,1),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(2,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(3,2), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,1),cell(4,3),cell(3,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(3,3), knownTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(2,4),cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4),cell(3,4),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), knownTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(4,2), knownTrue).

%% ── Category: knownFalse (65 examples) ──
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(2,3), knownFalse).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3)])],
       [], cell(2,1), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(2,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(4,2),cell(3,3),cell(4,3),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(2,1), knownFalse).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(1,2), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(3,1)])],
       [], cell(2,3), knownFalse).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(2,3), knownFalse).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(4,1),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(3,1),cell(4,2),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownFalse).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2)]),eatwumpus(orTrue,[])],
       [stench], cell(2,1), knownFalse).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(4,4)]),eatwumpus(orTrue,[])],
       [stench], cell(2,1), knownFalse).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [], cell(1,1), knownFalse).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [], cell(1,3), knownFalse).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,4), knownFalse).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(4,1),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(3,1),cell(4,2)]),eatwumpus(orTrue,[])],
       [stench], cell(4,2), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(4,4),cell(3,4),cell(2,4),cell(2,3)]),eatwumpus(orTrue,[])],
       [stench], cell(4,1), knownFalse).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(1,2), knownFalse).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[cell(2,3),cell(3,4)])],
       [], cell(2,2), knownFalse).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,4),cell(3,2),cell(4,2),cell(3,1)]),eatwumpus(orTrue,[])],
       [], cell(2,3), knownFalse).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownFalse).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3),cell(1,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownFalse).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(2,2), knownFalse).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,3),cell(3,2),cell(4,2),cell(3,1),cell(4,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownFalse).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(2,4),cell(3,4)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(4,4)])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownFalse).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[cell(3,3),cell(2,4)])],
       [], cell(2,2), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(4,2),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(1,3), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(1,2), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3)]),eatwumpus(orTrue,[cell(3,2),cell(2,3)])],
       [stench], cell(1,3), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(3,3),cell(2,4)])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(4,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(3,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [stench], cell(2,4), knownFalse).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(3,1),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(3,2),cell(4,3),cell(4,4),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(2,1), knownFalse).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,3),cell(4,1)]),eatwumpus(orTrue,[cell(1,3),cell(2,4)])],
       [], cell(4,2), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(1,2), knownFalse).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(1,2), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,1),cell(1,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(2,1), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(4,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(2,3), knownFalse).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [], cell(1,2), knownFalse).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(2,4),cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,2),cell(4,2),cell(3,3),cell(3,1),cell(4,3),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownFalse).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(1,4),cell(2,4),cell(3,4)]),eatwumpus(orTrue,[])],
       [], cell(1,4), knownFalse).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[cell(3,3),cell(4,4),cell(2,4)])],
       [], cell(1,2), knownFalse).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(2,3),cell(3,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(4,2),cell(3,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,1),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(2,1), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,1),cell(4,3),cell(3,4),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(3,2), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(3,3),cell(1,3),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(2,1), knownFalse).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(3,1)])],
       [], cell(2,3), knownFalse).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[cell(4,1),cell(3,2),cell(4,3)])],
       [], cell(3,3), knownFalse).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(3,1),cell(4,1),cell(4,2)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(3,3), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [stench], cell(3,4), knownFalse).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(2,2), knownFalse).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,3),cell(3,4),cell(4,4),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,3), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[cell(4,3),cell(3,4),cell(3,2)])],
       [], cell(1,3), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(1,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(3,3),cell(2,4),cell(4,3),cell(3,4),cell(4,4),cell(4,2),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[cell(3,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(1,1), knownFalse).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[cell(4,3),cell(3,4),cell(3,2)])],
       [], cell(1,2), knownFalse).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(3,1), knownFalse).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(4,4),cell(4,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(2,3), knownFalse).

%% ── Category: orTrue (65 examples) ──
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [], cell(3,1), orTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(2,4),cell(3,4)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(4,4)])],
       [stench], cell(4,4), orTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4)]),eatwumpus(orTrue,[cell(2,3),cell(3,4)])],
       [], cell(2,3), orTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(1,3), orTrue).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3)]),eatwumpus(orTrue,[cell(2,3),cell(1,4)])],
       [stench], cell(2,3), orTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4),cell(3,4),cell(2,4)]),eatwumpus(orTrue,[cell(2,3),cell(1,4)])],
       [stench], cell(2,3), orTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(3,1)])],
       [], cell(4,2), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1)]),eatwumpus(orTrue,[cell(3,2),cell(2,3),cell(4,1)])],
       [], cell(2,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3)])],
       [], cell(1,3), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3)])],
       [stench], cell(4,2), orTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(4,4),cell(4,3),cell(4,2)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [stench], cell(4,1), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(2,2), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(4,3), orTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4)]),eatwumpus(orTrue,[cell(2,3),cell(1,4),cell(3,4)])],
       [], cell(1,4), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2)]),eatwumpus(orTrue,[cell(4,2),cell(3,3)])],
       [stench], cell(4,2), orTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[cell(2,3),cell(1,4),cell(3,4)])],
       [], cell(1,4), orTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(1,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,1)])],
       [], cell(3,1), orTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(2,2), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(2,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(4,3), orTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[cell(3,2)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [stench], cell(4,3), orTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,2)]),eatwumpus(orTrue,[cell(3,3),cell(2,4)])],
       [], cell(3,3), orTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(4,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(3,4),cell(1,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,1)])],
       [], cell(3,1), orTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(2,3),cell(3,4)]),eatwumpus(orTrue,[cell(1,3),cell(2,4)])],
       [], cell(1,3), orTrue).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(2,4)]),eatwumpus(orTrue,[cell(4,2),cell(3,3)])],
       [], cell(4,2), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [], cell(1,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [], cell(3,1), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(3,3),cell(1,3),cell(2,4),cell(1,4),cell(4,2)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(4,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [], cell(2,2), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [], cell(1,3), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1)]),eatwumpus(orTrue,[cell(3,2),cell(2,3),cell(4,1)])],
       [], cell(3,2), orTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3)])],
       [stench], cell(1,3), orTrue).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(4,4)]),eatwumpus(orTrue,[cell(2,3),cell(3,4)])],
       [], cell(2,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,1)]),eatwumpus(orTrue,[cell(4,3),cell(3,4),cell(3,2),cell(4,1)])],
       [], cell(4,1), orTrue).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[cell(4,3),cell(3,4),cell(3,2)])],
       [], cell(4,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [], cell(2,2), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(1,1)]),eatwumpus(orTrue,[cell(2,1),cell(1,2)])],
       [stench], cell(2,1), orTrue).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3)]),eatwumpus(orTrue,[cell(2,3),cell(3,4)])],
       [], cell(3,4), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4),cell(2,3),cell(3,4)]),eatwumpus(orTrue,[cell(1,3),cell(2,4)])],
       [], cell(2,4), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3)]),eatwumpus(orTrue,[cell(3,2),cell(2,3),cell(1,4)])],
       [], cell(2,3), orTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3)]),eatwumpus(orTrue,[cell(4,1),cell(3,2),cell(4,3)])],
       [stench], cell(4,1), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(3,1)])],
       [stench], cell(4,2), orTrue).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(1,4),cell(3,4)]),eatwumpus(orTrue,[cell(4,2),cell(3,1)])],
       [], cell(3,1), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(3,1), orTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4)]),eatwumpus(orTrue,[cell(2,3),cell(1,4),cell(3,4)])],
       [stench], cell(1,4), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [], cell(1,3), orTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(2,3),cell(1,4),cell(3,3),cell(2,4)]),eatwumpus(orTrue,[cell(3,2),cell(4,1),cell(4,3),cell(3,4)])],
       [stench], cell(4,1), orTrue).
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3)]),eatwumpus(orTrue,[cell(3,3),cell(4,4)])],
       [], cell(4,4), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(1,1)]),eatwumpus(orTrue,[cell(2,1),cell(1,2)])],
       [stench], cell(2,1), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1)]),eatwumpus(orTrue,[cell(3,2),cell(2,3),cell(4,1)])],
       [], cell(2,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(1,1)]),eatwumpus(orTrue,[cell(2,1),cell(1,2)])],
       [stench], cell(1,2), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[cell(2,3),cell(1,4)])],
       [], cell(2,3), orTrue).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,3),cell(2,4),cell(1,4),cell(3,4),cell(4,4),cell(4,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,1)])],
       [], cell(4,2), orTrue).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(2,3),cell(3,4)]),eatwumpus(orTrue,[cell(4,4),cell(2,4)])],
       [], cell(2,4), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,3),cell(2,4),cell(3,2),cell(4,2),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[cell(4,3),cell(3,4)])],
       [], cell(4,3), orTrue).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [], cell(3,1), orTrue).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3),cell(4,4)]),eatwumpus(orTrue,[cell(4,1),cell(3,2),cell(4,3)])],
       [], cell(4,3), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[cell(3,3),cell(4,4),cell(2,4)])],
       [stench], cell(2,4), orTrue).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4)]),eatwumpus(orTrue,[cell(3,3),cell(2,4)])],
       [], cell(3,3), orTrue).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[cell(2,3),cell(1,4),cell(4,3),cell(3,4)])],
       [], cell(3,4), orTrue).

%% ── Category: unknown (65 examples) ──
wumpus(cell(4,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(4,3)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [stench], cell(3,3), unknown).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(1,3), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(1,1)]),eatwumpus(orTrue,[cell(2,1),cell(1,2)])],
       [stench], cell(4,3), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(1,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(3,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(2,3), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(3,2),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[cell(3,3),cell(2,4),cell(4,2)])],
       [stench], cell(4,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(1,4), unknown).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [], cell(4,4), unknown).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[cell(4,3),cell(2,3),cell(3,4)])],
       [], cell(2,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(1,4), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[cell(4,2),cell(3,3),cell(3,1)])],
       [], cell(1,4), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(1,3), unknown).
wumpus(cell(3,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), unknown).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(3,2), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [stench], cell(4,1), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(1,3), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [], cell(4,1), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(3,3), unknown).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3),cell(4,3),cell(3,2)]),eatwumpus(orTrue,[])],
       [], cell(4,2), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [stench], cell(4,3), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(4,3), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3)])],
       [], cell(3,2), unknown).
wumpus(cell(2,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(1,3),cell(1,4),cell(2,4),cell(3,4)]),eatwumpus(orTrue,[cell(4,4),cell(3,3)])],
       [], cell(4,3), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(2,2),cell(1,3),cell(3,1)])],
       [stench], cell(2,4), unknown).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[cell(3,2),cell(4,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4),cell(3,4),cell(4,4),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(4,2), unknown).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), unknown).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [stench], cell(4,2), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(4,1), unknown).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(4,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(3,1),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(4,3), unknown).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(3,1), unknown).
wumpus(cell(4,3),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(4,1),cell(4,3)]),eatwumpus(orTrue,[])],
       [stench], cell(1,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [], cell(3,2), unknown).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(2,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[cell(3,3),cell(2,4)])],
       [stench], cell(3,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [], cell(4,3), unknown).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2)]),eatwumpus(orTrue,[cell(4,1),cell(3,2)])],
       [stench], cell(2,4), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2),cell(1,3)])],
       [stench], cell(2,4), unknown).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2)]),eatwumpus(orTrue,[])],
       [], cell(1,4), unknown).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(3,3),cell(1,3),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(3,4), unknown).
wumpus(cell(3,2),
       [eatwumpus(knownTrue,[cell(1,3)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(4,2),cell(3,3)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(1,3),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(1,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1)]),eatwumpus(orTrue,[cell(3,2),cell(2,3),cell(4,1)])],
       [], cell(1,4), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(3,4), unknown).
wumpus(cell(3,3),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(3,3),cell(4,3),cell(4,4)]),eatwumpus(orTrue,[cell(2,3),cell(3,4)])],
       [stench], cell(1,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[cell(3,1),cell(2,2)])],
       [stench], cell(1,3), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(1,4),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(2,3),cell(1,4),cell(2,4)]),eatwumpus(orTrue,[])],
       [], cell(3,2), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(3,1)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(3,4), unknown).
wumpus(cell(3,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2)]),eatwumpus(orTrue,[])],
       [], cell(3,3), unknown).
wumpus(cell(1,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(1,2),
       [eatwumpus(knownTrue,[cell(4,4)]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(4,1),cell(3,2),cell(4,2),cell(4,3),cell(3,3),cell(2,3),cell(1,3)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(2,2),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2),cell(3,2),cell(2,3),cell(3,3),cell(1,3),cell(2,4),cell(1,4)]),eatwumpus(orTrue,[])],
       [], cell(4,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(3,1),cell(2,2)]),eatwumpus(orTrue,[])],
       [], cell(4,1), unknown).
wumpus(cell(4,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,2),cell(2,3),cell(4,2),cell(3,3),cell(3,1),cell(4,1)]),eatwumpus(orTrue,[])],
       [], cell(2,4), unknown).
wumpus(cell(2,1),
       [eatwumpus(knownTrue,[]),eatwumpus(knownFalse,[cell(2,1),cell(1,2),cell(1,1),cell(2,2),cell(1,3),cell(3,1)]),eatwumpus(orTrue,[cell(3,2),cell(2,3)])],
       [], cell(2,4), unknown).

:- end_in_pos.
